#!/usr/bin/env node
/**
 * gen.mjs — regenerate the manual's skills map + core/role pages from the
 * canonical skill store (~/.agents/skills) and the decision trees in trees.mjs.
 *
 * Single source of truth = SKILL.md frontmatter (domain / role / order /
 * load_when / guidance) + the full body. Emits:
 *   - src/content/docs/core.md            (core skills, full content)
 *   - src/content/docs/roles/<domain>.md  (decision tree + domain skills, full)
 *   - src/content/docs/skills.md          (the map: skill → load_when)
 *
 * Usage: node manual/scripts/gen.mjs
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { TREES } from "./trees.mjs";

const SKILLS = "/Users/sebroot/.agents/skills";
const DOCS = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "content", "docs");

const DOMAINS = ["core", "pm", "qa", "security", "backend", "frontend", "devops", "ai-ml"];
const LABEL = {
  core: "Core", pm: "PM", qa: "QA", security: "Security",
  backend: "Backend", frontend: "Frontend / Designer", devops: "DevOps", "ai-ml": "AI / ML",
};
const NOTE = {
  pm: "the guava-os manager session", qa: "`reviewer`", security: "`security-reviewer`",
  backend: "`task` / `sonic`", frontend: "`designer` / `task`",
  devops: "`task`", "ai-ml": "`task` / `scout`",
};

function parseSkill(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return null;
  const fm = { name: "", description: "", domain: "", role: "", order: 0, load_when: "" };
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (!kv) continue;
    let val = kv[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    if (kv[1] === "order") fm.order = Number(val) || 0;
    else if (kv[1] in fm) fm[kv[1]] = val;
  }
  return { frontmatter: fm, body: m[2].trim() };
}

async function loadSkills() {
  const dirs = await readdir(SKILLS, { withFileTypes: true });
  const out = [];
  for (const d of dirs) {
    if (!d.isDirectory()) continue;
    let text;
    try { text = await readFile(join(SKILLS, d.name, "SKILL.md"), "utf8"); } catch { continue; }
    const s = parseSkill(text);
    if (s && s.frontmatter.name) out.push(s);
  }
  return out;
}

function group(skills) {
  const by = {};
  for (const d of [...DOMAINS, "ecosystem"]) by[d] = [];
  for (const s of skills) {
    const dom = DOMAINS.includes(s.frontmatter.domain) ? s.frontmatter.domain : "ecosystem";
    by[dom].push(s);
  }
  for (const k of Object.keys(by)) {
    by[k].sort((a, b) => (a.frontmatter.order - b.frontmatter.order) || a.frontmatter.name.localeCompare(b.frontmatter.name));
  }
  return by;
}

function skillSection(s) {
  return `### ${s.frontmatter.name}\n\n_${s.frontmatter.description}_\n\n${s.body}\n\n`;
}

function treeMermaid(domain, tree) {
  const lines = ["flowchart TD"];
  lines.push("    CORE[Core — always loaded]");
  lines.push(`    CORE --> Q{${tree.question}}`);
  tree.branches.forEach((b, i) => {
    lines.push(`    Q -->|${b.label}| B${i}[${b.skills.join(" \\u2192 ")}]`);
  });
  return lines.join("\n");
}

const cell = (s) => (s || "").replace(/\|/g, "/");

async function main() {
  const skills = await loadSkills();
  const by = group(skills);

  // ── core.md ──
  let core = `---\ntitle: Core\ndescription: "The small, stable layer every agent loads before domain work."\n---\n\n# Core\n\n`;
  core += `Loaded by every agent, and used *with* role-specific skills. The engine of the\ncore is \`engineering-principles\` (\`## Invariants\` → \`## Execution protocol\` →\n\`## Completion contract\`), which the injector pulls verbatim.\n\n`;
  for (const s of by.core) core += skillSection(s);
  await writeFile(join(DOCS, "core.md"), core);

  // ── role pages ──
  for (const d of DOMAINS) {
    if (d === "core") continue;
    const list = by[d];
    const tree = TREES[d];
    let page = `---\ntitle: "${LABEL[d]}"\ndescription: "Full ${LABEL[d]} role context: decision tree + skills, in order."\n---\n\n# ${LABEL[d]}\n\n`;
    page += `Dispatched as ${NOTE[d]}. Load **Core** first, then follow the tree below.\n\n`;
    if (tree) {
      page += `## Decision tree\n\n\`\`\`mermaid\n${treeMermaid(d, tree)}\n\`\`\`\n\n`;
    }
    page += `## Skills\n\n`;
    for (const s of list) page += skillSection(s);
    await writeFile(join(DOCS, "roles", `${d}.md`), page);
  }

  // ── skills.md (the map) ──
  let map = `---\ntitle: Skills\ndescription: "The map: every skill, its domain, dispatching agent, and when to load it."\n---\n\n# Skills\n\n`;
  map += `Canonical store: \`~/.agents/skills/<name>/SKILL.md\` (generated by \`manual/scripts/gen.mjs\`). Each domain links to its full-content page.\n\n`;
  for (const d of DOMAINS) {
    const list = by[d];
    if (list.length === 0) continue;
    const link = d === "core" ? "/core/" : `/roles/${d}/`;
    map += `## [${LABEL[d]}](${link}) (${list.length})\n\n`;
    map += `| Skill | Agent | load_when |\n|---|---|---|\n`;
    for (const s of list) {
      map += `| \`${s.frontmatter.name}\` | ${cell(s.frontmatter.role)} | ${cell(s.frontmatter.load_when || s.frontmatter.description)} |\n`;
    }
    map += `\n`;
  }
  if (by.ecosystem.length) {
    map += `## Ecosystem / unassigned (${by.ecosystem.length})\n\n| Skill | Agent | load_when |\n|---|---|---|\n`;
    for (const s of by.ecosystem) {
      map += `| \`${s.frontmatter.name}\` | ${cell(s.frontmatter.role || "—")} | ${cell(s.frontmatter.load_when || s.frontmatter.description)} |\n`;
    }
    map += `\n`;
  }
  await writeFile(join(DOCS, "skills.md"), map);

  console.log(`Generated core.md + ${DOMAINS.length - 1} role pages + skills.md from ${skills.length} skills.`);
  console.log("Ecosystem:", by.ecosystem.map((s) => s.frontmatter.name).join(", ") || "(none)");
}

main().catch((e) => { console.error(e); process.exit(1); });